owner: makeproaudio
repo: status

sites:
  - name: Website
    url: https://my.makepro-x.com
  - name: Cloud Service
    url: https://my.makepro-x.com
  - name: Authentication
    url: $URL_AUTH
  - name: Forum
    url: https://forum.makepro-x.com
  - name: CDN (Downloads)
    url: $URL_CDN

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/makeproaudio/status/master/assets/x_black_transparent_rect.png
  name: MakePro X Cloud Status
  introTitle: "Status Information about the services of the **MakePro X Cloud**"
  introMessage: ""
  navbar:
    - title: Status
      href: /